
package com.test;

import java.util.Date;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeatherServiceImpl", targetNamespace = "http://www.wuxianedu.com/ws/weather")
public interface WeatherService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.wuxianedu.ws.weather.TemperatureInfo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWeathers", targetNamespace = "http://www.wuxianedu.com/ws/weather", className = "com.wuxianedu.ws.weather.GetWeathers")
    @ResponseWrapper(localName = "getWeathersResponse", targetNamespace = "http://www.wuxianedu.com/ws/weather", className = "com.wuxianedu.ws.weather.GetWeathersResponse")
    @Action(input = "http://www.wuxianedu.com/ws/weather/WeatherServiceImpl/getWeathersRequest", output = "http://www.wuxianedu.com/ws/weather/WeatherServiceImpl/getWeathersResponse")
    public List<TemperatureInfo> getWeathers(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        List<Date> arg1);

}
